name: Chat app Node-Js

on:
  push:
    branches:
      - feature/chat-app
  pull_request:
    branches:
      - feature/chat-app

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/feature/chat-app'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Linking project to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NODE_ENV: ${{ secrets.NODE_ENV }}    
      run: npx vercel link --yes --project node-js-chat-app --token=${{ secrets.VERCEL_TOKEN }}

    - name: Run migrations
      run: npx knex migrate:latest --env  ${{ secrets.NODE_ENV }}

    - name: Deploy to vercel
      run: npx vercel --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
      